#
# Copyright 2017-2019 Martin Goellnitz.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

- name: Extract Apache Maven
  unarchive:
    src: "http://www.apache.org/dist/maven/maven-{{ maven_major }}/{{ maven_version }}/binaries/apache-maven-{{ maven_version }}-bin.tar.gz"
    dest: "{{maven_home_parent_directory}}"
    copy: no

- name: Maven path configuration
  template: src=maven.sh dest=/etc/profile.d/maven.sh

#- name: Remove old Maven path configuration
#  file:
#    path: /etc/profile.d/maven.sh
#    state: absent
#
#- name: Maven path configuration
#  lineinfile:
#    dest: /etc/profile.d/maven.sh
#    line: "{{ item.line }}"
#    create: yes
#    state: present
#  with_items:
#    - { line: 'M2_HOME={{maven_home_parent_directory}}/apache-maven-{{maven_version}}' }
#    - { line: 'PATH=$PATH:$M2_HOME/bin' }
